### ISSUE TITLE
Convert to namespace plugin and apply new template

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/neighbors#1]
Since @kdeldycke [graciously offered](https://github.com/getpelican/pelican-plugins/issues/1287) to help migrate the [Neighbors plugin](https://github.com/getpelican/pelican-plugins/tree/master/neighbors) from the legacy monolithic repository, I have created a new repository here and performed all the steps listed under **Initial Setup (By Maintainer)** here: https://blog.getpelican.com/drafts/namespace-plugin-migration.html

The remaining steps to be done are listed in the [**Updating the Plugin**](https://blog.getpelican.com/drafts/namespace-plugin-migration.html#updating-the-plugin) section further down the page. Be sure to change the example plugin name in the listed commands to match the current plugin name.

**Comment by justinmayer** [comment]
@kdeldycke: Thanks again for offering to help with this! The above guide is still a draft, so please let me know if you have any questions or suggestions for improving it. As a reference, I used the [Series plugin](https://github.com/pelican-plugins/series) as an example and performed all the steps from the above guide, resulting in the commits you see in its [`migrate` branch](https://github.com/pelican-plugins/series/compare/migrate).

Once the same steps have been performed for the Neighbors plugin and its `migrate` branch has been pushed, please open a pull request so that branch can be merged into `main`. After merging, we can close this issue and move on to deployment automation. 🚀

**Comment by kdeldycke** [comment]
Looking into all that stuff right now! Thanks @justinmayer for opening up the repo! 👍

**Comment by kdeldycke** [comment]
Everything's ready to be reviewed in #2 PR. Thanks @justinmayer for the preparation on the `migrate` branch. You really made the job easy with your tutorial at: https://blog.getpelican.com/drafts/namespace-plugin-migration.html .

I've seen a couple area of improvement on the cookie cutter template but that's essentially nitpicking. You did an awesome job documenting and preparing the migration path. I'll probably offer to migrate some more plugins I rely on if you wish! 😺

**Comment by justinmayer** [comment]
@kdeldycke: Thanks again for your work getting the Neighbors plugin migrated. Sometime over the next week I'll find time to add CI/deployment automation steps to the migration guide, after which we can get the next version of this plugin published to PyPI. 🤖 

> I'll probably offer to migrate some more plugins I rely on if you wish!

That would be fantastic and most welcome. By all means, please do! 😁
